services:
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  celery:
    build: .
    command: celery -A PungDuc_BE worker -l info -P gevent
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A PungDuc_BE beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge