services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: phucquach2002
      POSTGRES_DB: PungDuc

    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - redis-network

  celery:
    build: .
    command: bash -c "celery -A PungDuc_BE worker -l info -P gevent"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - app

  celery-beat:
    build: .
    command: bash -c "celery -A PungDuc_BE beat -l INFO"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - app

networks:
  redis-network:
    driver: bridge
  db:
    driver: bridge